Repository LorettaDevs/Loretta, pull requests merged in 2021-12, with the labels that each got.

#39 Implement Luau's if expression
  CHANGES.md
  src/Compilers/Lua/Portable/Errors/ErrorCode.cs
  src/Compilers/Lua/Portable/LuaResources.Designer.cs
  src/Compilers/Lua/Portable/LuaResources.resx
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/Parser/LanguageParser.cs
  src/Compilers/Lua/Portable/Syntax/Syntax.xml
  src/Compilers/Lua/Portable/Syntax/SyntaxKind.cs
Labels: enhancement

#40 Fix some parser errors
  CHANGES.md
  src/Compilers/Lua/Portable/Errors/ErrorCode.cs
  src/Compilers/Lua/Portable/LuaResources.Designer.cs
  src/Compilers/Lua/Portable/LuaResources.resx
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/Parser/LanguageParser.cs
  src/Compilers/Lua/Portable/Script/ScopeAndVariableManager.GotoWalker.cs
  src/Compilers/Lua/Portable/Script/ScopeAndVariableManager.ScopeAndVariableWalker.cs
  src/Compilers/Lua/Portable/Syntax/Syntax.xml
  src/Compilers/Lua/Portable/Syntax/SyntaxKind.cs
  src/Compilers/Lua/Test/Syntax/Lexical/LexicalErrorTests.cs
  src/Compilers/Lua/Test/Syntax/Lexical/LexicalTests.cs
Labels: bug, version-Luau, version-Lua5.1, version-Lua5.2, version-Lua5.3, version-LuaJIT2.1, version-Lua5.4

#37 Improve SyntaxNormalizer
  src/Compilers/Lua/Portable/Syntax/SyntaxNormalizer.cs
Labels: enhancement, version-Luau, version-Lua5.1, version-Lua5.2, version-Lua5.3, version-LuaJIT2.1, version-Lua5.4

#43 Implement FiveM hash strings
  CHANGES.md
  src/Compilers/Core/Portable/InternalUtilities/Hash.cs
  src/Compilers/Lua/Portable/Errors/ErrorCode.cs
  src/Compilers/Lua/Portable/LuaResources.Designer.cs
  src/Compilers/Lua/Portable/LuaResources.resx
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/Parser/LanguageParser.cs
  src/Compilers/Lua/Portable/Parser/Lexer.ShortString.cs
  src/Compilers/Lua/Portable/Parser/Lexer.cs
  src/Compilers/Lua/Portable/Syntax/InternalSyntax/SyntaxFactory.cs
  src/Compilers/Lua/Portable/Syntax/Syntax.xml
  src/Compilers/Lua/Portable/Syntax/SyntaxKind.cs
  src/Compilers/Lua/Test/Syntax/Lexical/LexicalErrorTests.cs
  src/Compilers/Lua/Test/Syntax/Lexical/LexicalTestData.cs
  src/Compilers/Lua/Test/Syntax/SyntaxKindTests.cs
Labels: enhancement, version-FiveM
