Repository LorettaDevs/Loretta, pull requests merged in 2022-03, with the labels that each got.

#68 Change Roblox to Luau
  CHANGES.md
  README.md
  docs/index.md
  src/Compilers/Lua/CommandLine/Program.cs
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/PublicAPI.Unshipped.txt
Labels: version-Luau

#69 Add floor division expression
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/Parser/Lexer.cs
  src/Compilers/Lua/Portable/PublicAPI.Shipped.txt
  src/Compilers/Lua/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Lua/Portable/Syntax/Syntax.xml
  src/Compilers/Lua/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/Lua/Portable/Syntax/SyntaxKind.cs
  src/Compilers/Lua/Test/Portable/Lexical/LexicalErrorTests.cs
  src/Compilers/Lua/Test/Portable/Lexical/LexicalTestData.cs
  src/Compilers/Lua/Test/Portable/Lexical/LexicalTests.cs
  src/Compilers/Lua/Test/Portable/Parsing/BinaryOperatorPrecedenceTests.cs
Labels: version-Lua5.3, version-Lua5.4

#73 Add LuaJIT suffixes "ULL" & "LL"
  CHANGES.md
  src/Compilers/Lua/Portable/Errors/ErrorCode.cs
  src/Compilers/Lua/Portable/LuaResources.Designer.cs
  src/Compilers/Lua/Portable/LuaResources.resx
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
  src/Compilers/Lua/Portable/Parser/Lexer.Numbers.cs
  src/Compilers/Lua/Portable/Parser/Lexer.cs
  src/Compilers/Lua/Portable/PublicAPI.Shipped.txt
  src/Compilers/Lua/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Lua/Portable/SymbolDisplay/ObjectDisplay.cs
  src/Compilers/Lua/Portable/Syntax/InternalSyntax/SyntaxFactory.cs
  src/Compilers/Lua/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/Lua/Test/Portable/Lexical/LexicalErrorTests.cs
  src/Compilers/Lua/Test/Portable/Lexical/LexicalTestData.cs
Labels: enhancement, version-LuaJIT2.1, version-LuaJIT2.0

#75 Review all presets
  CHANGES.md
  src/Compilers/Lua/Portable/LuaSyntaxOptions.cs
Labels: bug, version-Luau, version-Lua5.1, version-Lua5.2, version-Lua5.3, version-LuaJIT2.1, version-Lua5.4, version-FiveM, version-LuaJIT2.0

#82 Add case insensitive test-cases
  src/Compilers/Lua/Test/Portable/Lexical/LexicalTestData.cs
Labels: enhancement, version-LuaJIT2.1, version-LuaJIT2.0

#84 Create the localizer tutorial
  docs/articles/experimental/minifier.md
  docs/docfx.json
  docs/images/logo.svg
  docs/templates/overrides/partials/head.tmpl.partial
  docs/templates/overrides/styles/logo.css
  docs/toc.yml
  docs/tutorials/creating-a-localizer/part-1.md
  docs/tutorials/creating-a-localizer/toc.yml
  docs/tutorials/toc.yml
Labels: docs
